/**
 * 一次性数据迁移：把**旧命名**的自动日志改成新命名。
 *
 * 背景：`/game start` 以前自动开的日志叫 `<桌名> · <MMDD-HHmm>`（后来还会叠成
 * `<桌名> · <时间戳> · <时间戳>`），现在改成「**用设定的名字**，未设定才回退带完整日期的桌名」，
 * 于是旧日志名要跟着迁：
 *   - **暂停中（off）**：只改记录里的名字——以后 `/log end name:<旧名>` 导出时文件名就是新的；
 *   - **已结束（ended）**：连 `fileName` 一起改，并把 `data/logs/` 下已导出的文件改名；
 *   - **正在记录（on）**：同样改名（不影响正在写的内容）。
 *
 * 判定「旧自动名」的规则（幂等，跑多少遍都一样）：
 *   `name === <桌名> · <时间戳>`，其中时间戳是旧格式 `MMDD-HHMM` 或新格式 `YYYY-MM-DD HHMM`，
 *   也允许重复叠加（`桌名 · 0918-0006 · 0918-0006`）。用户自己取的名字（`阿卡姆 · 第一夜`）不动。
 *
 * 用法：`node --env-file-if-exists=.env scripts/migrate-log-names.ts [--apply]`（默认 dry-run）。
 */
import { existsSync, renameSync } from 'node:fs';
import { join } from 'node:path';

import type { GameRecord, LogRecord } from '../contracts/model.ts';
import { diceLogFileName, diceLogSessionName } from './logFormat.ts';

/** 旧 `fmtStamp`：`MMDD-HHmm`（4 位月日 + `-` + 4 位时分）；新 `fmtStamp`：`YYYY-MM-DD HHMM`。 */
const STAMP_PATTERNS = [/^\d{4}-\d{4}$/, /^\d{4}-\d{2}-\d{2} \d{4}$/];

/** `log.name` 是不是 `<桌名> · <时间戳> [· <时间戳>…]` 这种**自动生成**的名字。 */
export function isAutoGeneratedLogName(name: string, gameName: string | null): boolean {
  if (!gameName) return false;
  const prefix = `${gameName} · `;
  if (!name.startsWith(prefix)) return false;
  const rest = name.slice(prefix.length).trim();
  if (rest.length === 0) return false;
  return rest
    .split(' · ')
    .every((part) => STAMP_PATTERNS.some((pattern) => pattern.test(part.trim())));
}

export interface LogNameChange {
  logId: string;
  from: string;
  to: string;
  /** 已结束日志要同步改的导出文件名（旧 → 新） */
  fileFrom?: string;
  fileTo?: string;
}

/** 目标名字在**同一局/同一会话**内不能重复（与 `createLog` 的 `uniqueLogName` 同口径）。 */
function uniqueName(taken: Set<string>, base: string): string {
  if (!taken.has(base)) return base;
  for (let i = 2; i < 1000; i += 1) {
    const candidate = `${base} (${i})`;
    if (!taken.has(candidate)) return candidate;
  }
  return `${base} (${Date.now()})`;
}

function fileFor(
  log: LogRecord,
  name: string,
  getGame: (guildId: string, gameId: string) => GameRecord | null,
): string {
  const next: LogRecord = { ...log, name, fileName: null };
  return diceLogFileName(
    diceLogSessionName(next, (guildId, gameId) => getGame(guildId, gameId)),
    name,
  );
}

/**
 * 算出需要改名的日志（纯函数，不改任何东西）。
 * `getGame` 用于拿桌名；查不到局的日志（场景日志 / 局已删）不迁移。
 */
export function planLogNameChanges(
  logs: LogRecord[],
  getGame: (guildId: string, gameId: string) => GameRecord | null,
): LogNameChange[] {
  const taken = new Map<string, Set<string>>();
  for (const log of logs) {
    const scope = `${log.guildId}\u0000${log.gameId ?? '@scene'}`;
    const names = taken.get(scope) ?? new Set<string>();
    names.add(log.name);
    taken.set(scope, names);
  }

  const changes: LogNameChange[] = [];
  const migrating = new Set<string>();
  for (const log of logs) {
    if (!log.gameId) continue;
    const game = getGame(log.guildId, log.gameId);
    if (!game || !isAutoGeneratedLogName(log.name, game.name)) continue;
    const scope = `${log.guildId}\u0000${log.gameId}`;
    const names = taken.get(scope) ?? new Set<string>();
    const to = uniqueName(names, game.name);
    names.add(to);
    migrating.add(log.id);
    changes.push({ logId: log.id, from: log.name, to });
  }

  // 导出文件名在同一**服务器**内也要唯一（与 jsonStore.logFilePath 同一套规则）：
  // 先把不迁移的日志占用的名字记下来，再按顺序给迁移项分配，冲突就加 `_<logId>`。
  const takenFiles = new Map<string, Set<string>>();
  const usedFiles = (guildId: string): Set<string> => {
    const set = takenFiles.get(guildId) ?? new Set<string>();
    takenFiles.set(guildId, set);
    return set;
  };
  for (const log of logs) {
    if (migrating.has(log.id)) continue;
    usedFiles(log.guildId).add(log.fileName ?? fileFor(log, log.name, getGame));
  }
  for (const change of changes) {
    const log = logs.find((candidate) => candidate.id === change.logId);
    if (!log || log.state !== 'ended' || !log.fileName) continue;
    const files = usedFiles(log.guildId);
    const base = fileFor(log, change.to, getGame);
    const fileTo = files.has(base) ? `${base.replace(/\.txt$/i, '')}_${log.id}.txt` : base;
    files.add(fileTo);
    change.fileFrom = log.fileName;
    change.fileTo = fileTo;
  }
  return changes;
}

/** 迁移需要的最小 store 形状（真实 jsonStore 与测试假件都满足）。 */
export interface MigrationStore {
  getLog(id: string): LogRecord | null;
  putLog(log: LogRecord): void;
  /** 真实 store 提供：复用它的「同服同名去重」逻辑算导出文件路径 */
  logFilePath?(log: LogRecord): string;
  flush?(): Promise<void> | void;
}

export interface MigrationResult {
  changes: LogNameChange[];
  renamedFiles: { from: string; to: string }[];
  warnings: string[];
}

/**
 * 执行迁移。`dryRun` **默认为 true**（安全：忘了传就只算不写，CLI 用 `--apply` 显式关闭）。
 * 文件名冲突（新名字的文件已存在）时不覆盖，只改记录并给出 warning。
 */
export async function migrateLogNames(
  store: MigrationStore,
  logIds: string[],
  getGame: (guildId: string, gameId: string) => GameRecord | null,
  options: { logsDir: string; dryRun?: boolean } = { logsDir: '' },
): Promise<MigrationResult> {
  const logs = logIds
    .map((id) => store.getLog(id))
    .filter((log): log is LogRecord => log !== null);
  const changes = planLogNameChanges(logs, getGame);
  const renamedFiles: { from: string; to: string }[] = [];
  const warnings: string[] = [];
  if (options.dryRun !== false) return { changes, renamedFiles, warnings };

  for (const change of changes) {
    const log = store.getLog(change.logId);
    if (!log) continue;
    const next: LogRecord = { ...log, name: change.to };
    if (change.fileFrom && change.fileTo) {
      const from = join(options.logsDir, change.fileFrom);
      const target = join(options.logsDir, change.fileTo);
      if (existsSync(from) && !existsSync(target)) {
        renameSync(from, target);
        renamedFiles.push({ from: change.fileFrom, to: change.fileTo });
      } else if (existsSync(target)) {
        warnings.push(`同名导出文件已存在，未覆盖：${change.fileTo}`);
      }
      next.fileName = change.fileTo;
    }
    store.putLog(next);
  }
  await store.flush?.();
  return { changes, renamedFiles, warnings };
}
