/**
 * 日志名迁移（`src/bot/migrateLogNames.ts`）：旧自动名 `<桌名> · <MMDD-HHmm>` → 桌名。
 * 覆盖：暂停中 / 已结束（含导出文件改名）/ 重复叠加 / 用户自取名不动 / 幂等。
 *
 * Run: node tests/bot/migrate-log-names.test.ts
 */
import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { isAutoGeneratedLogName, migrateLogNames, planLogNameChanges } from '../../src/bot/migrateLogNames.ts';
import type { GameRecord, LogRecord } from '../../src/contracts/model.ts';
import { createJsonStoreWithExtras } from '../../src/store/jsonStore.ts';

const TMP_ROOT = fileURLToPath(new URL('../.tmp/', import.meta.url));

function tempDir(label: string): string {
  mkdirSync(TMP_ROOT, { recursive: true });
  return mkdtempSync(join(TMP_ROOT, `migrate-${label}-`));
}

function game(id: string, name: string, guildId = 'G1'): GameRecord {
  return {
    id,
    guildId,
    name,
    keeperId: 'KP1',
    status: 'active',
    sceneThreadId: null,
    parentChannelId: 'C1',
    sceneThreadCreatedByBot: false,
    hiddenThreadId: null,
    rule: null,
    currentLogId: null,
    startedAt: '2026-01-01T00:00:00.000Z',
    endedAt: null,
  };
}

function log(spec: Partial<LogRecord> & { id: string; name: string }): LogRecord {
  return {
    gameId: '#1',
    channelId: 'C1',
    guildId: 'G1',
    state: 'off',
    sceneIds: ['C1'],
    startedAt: '2026-01-01T00:00:00.000Z',
    endedAt: null,
    fileName: null,
    ...spec,
  };
}

describe('isAutoGeneratedLogName', () => {
  test('认旧格式 MMDD-HHMM、新格式 YYYY-MM-DD HHMM，以及重复叠加', () => {
    assert.equal(isAutoGeneratedLogName('阿卡姆 · 0918-2202', '阿卡姆'), true);
    assert.equal(isAutoGeneratedLogName('阿卡姆 · 2026-09-18 2202', '阿卡姆'), true);
    assert.equal(isAutoGeneratedLogName('测试骰娘 · 0918-0006 · 0918-0006', '测试骰娘 · 0918-0006'), true);
  });

  test('用户自己取的名字、桌名本身、空桌名都不算', () => {
    assert.equal(isAutoGeneratedLogName('阿卡姆 · 第一夜', '阿卡姆'), false);
    assert.equal(isAutoGeneratedLogName('阿卡姆', '阿卡姆'), false);
    assert.equal(isAutoGeneratedLogName('阿卡姆 · 0918-2202', null), false);
    assert.equal(isAutoGeneratedLogName('别的桌 · 0918-2202', '阿卡姆'), false);
    assert.equal(isAutoGeneratedLogName('阿卡姆 · ', '阿卡姆'), false);
  });
});

describe('planLogNameChanges', () => {
  const games: Record<string, GameRecord> = { '#1': game('#1', '阿卡姆') };
  const getGame = (_guildId: string, gameId: string): GameRecord | null => games[gameId] ?? null;

  test('自动名 → 桌名；用户命名不动；场景日志不动', () => {
    const changes = planLogNameChanges(
      [
        log({ id: 'L1', name: '阿卡姆 · 0918-2202', state: 'off' }),
        log({ id: 'L2', name: '第一夜', state: 'on' }),
        log({ id: 'L3', name: '单人团', state: 'off', gameId: null }),
        log({ id: 'L4', name: '阿卡姆 · 2026-09-18 2202', state: 'off' }),
      ],
      getGame,
    );
    assert.deepEqual(
      changes.map((change) => [change.logId, change.from, change.to]),
      [
        ['L1', '阿卡姆 · 0918-2202', '阿卡姆'],
        // 同一局里已经有「阿卡姆」了 → 第二条自动加序号
        ['L4', '阿卡姆 · 2026-09-18 2202', '阿卡姆 (2)'],
      ],
    );
  });

  test('同一局内重名自动加序号（迁移后不会两条同名）', () => {
    const changes = planLogNameChanges(
      [
        log({ id: 'L1', name: '阿卡姆 · 0918-2202', state: 'off' }),
        log({ id: 'L2', name: '阿卡姆 · 0918-2302', state: 'off' }),
        log({ id: 'L3', name: '阿卡姆', state: 'on' }), // 已经叫桌名的那条（比如迁移过）
      ],
      getGame,
    );
    assert.deepEqual(
      changes.map((change) => change.to),
      ['阿卡姆 (2)', '阿卡姆 (3)'],
    );
  });

  test('已结束日志带上导出文件名（新命名规则算出来）', () => {
    const changes = planLogNameChanges(
      [log({ id: 'L1', name: '阿卡姆 · 0918-2202', state: 'ended', fileName: '阿卡姆_阿卡姆 · 0918-2202.txt' })],
      getGame,
    );
    assert.equal(changes.length, 1);
    assert.equal(changes[0]?.fileFrom, '阿卡姆_阿卡姆 · 0918-2202.txt');
    assert.equal(changes[0]?.fileTo, '阿卡姆.txt', '会话名 = 日志名 → 省略重复段');
  });
  test('用户命名过的日志与已结束的旧格式：只动自动名', () => {
    const changes = planLogNameChanges(
      [
        log({ id: 'L1', name: '阿卡姆 · 第一夜', state: 'ended', fileName: '阿卡姆_阿卡姆 · 第一夜.txt' }),
        log({ id: 'L2', name: '阿卡姆 · 0918-2202', state: 'ended', fileName: '第一夜.txt' }),
      ],
      getGame,
    );
    assert.deepEqual(changes.map((change) => change.logId), ['L2']);
  });
});

describe('migrateLogNames（真实 jsonStore 落盘）', () => {
  test('暂停中的日志只改记录；已结束的连文件名一起改；重跑幂等', async () => {
    const dir = tempDir('apply');
    const logsDir = join(dir, 'logs');
    mkdirSync(logsDir, { recursive: true });
    const store = createJsonStoreWithExtras({ dir });
    store.putGame(game('#1', '阿卡姆'));
    store.putLog(log({ id: 'L1', name: '阿卡姆 · 0918-2202', state: 'off' }));
    store.putLog(log({ id: 'L2', name: '阿卡姆 · 0918-2302', state: 'on' }));
    store.putLog(
      log({ id: 'L3', name: '阿卡姆 · 0918-2359', state: 'ended', fileName: '阿卡姆_阿卡姆 · 0918-2359.txt' }),
    );
    writeFileSync(join(logsDir, '阿卡姆_阿卡姆 · 0918-2359.txt'), '旧日志内容', 'utf8');
    await store.flush();

    const first = await migrateLogNames(
      store,
      ['L1', 'L2', 'L3'],
      (guildId, gameId) => store.getGame(guildId, gameId),
      { logsDir, dryRun: false },
    );
    assert.equal(first.changes.length, 3);
    assert.deepEqual(first.renamedFiles, [
      { from: '阿卡姆_阿卡姆 · 0918-2359.txt', to: '阿卡姆_阿卡姆 (3).txt' },
    ]);

    assert.equal(store.getLog('L1')?.name, '阿卡姆');
    assert.equal(store.getLog('L2')?.name, '阿卡姆 (2)', '同局内自动加序号');
    assert.equal(store.getLog('L3')?.name, '阿卡姆 (3)');
    assert.equal(store.getLog('L3')?.fileName, '阿卡姆_阿卡姆 (3).txt');
    assert.equal(existsSync(join(logsDir, '阿卡姆_阿卡姆 (3).txt')), true);
    assert.equal(existsSync(join(logsDir, '阿卡姆_阿卡姆 · 0918-2359.txt')), false);
    assert.equal(readdirSync(logsDir).length, 1);

    // 暂停中的日志 fileName 仍是 null（导出时才生成新名字），状态不变
    assert.equal(store.getLog('L1')?.fileName, null);
    assert.equal(store.getLog('L1')?.state, 'off');

    // 重跑：没有可迁移的了
    const again = await migrateLogNames(
      store,
      ['L1', 'L2', 'L3'],
      (guildId, gameId) => store.getGame(guildId, gameId),
      { logsDir, dryRun: false },
    );
    assert.equal(again.changes.length, 0, '迁移必须幂等');
  });

  test('dry-run 只算不写', async () => {
    const dir = tempDir('dry');
    const logsDir = join(dir, 'logs');
    mkdirSync(logsDir, { recursive: true });
    const store = createJsonStoreWithExtras({ dir });
    store.putGame(game('#1', '阿卡姆'));
    store.putLog(log({ id: 'L1', name: '阿卡姆 · 0918-2202', state: 'off' }));
    writeFileSync(join(logsDir, '阿卡姆_阿卡姆 · 0918-2202.txt'), 'x', 'utf8');

    const result = await migrateLogNames(
      store,
      ['L1'],
      (guildId, gameId) => store.getGame(guildId, gameId),
      { logsDir, dryRun: true },
    );
    assert.equal(result.changes.length, 1);
    assert.equal(store.getLog('L1')?.name, '阿卡姆 · 0918-2202', 'dry-run 不得改数据');
  });

  test('同服两条日志迁移后文件名不撞车（第二条自动加 _<logId>）', async () => {
    const dir = tempDir('filecollision');
    const logsDir = join(dir, 'logs');
    mkdirSync(logsDir, { recursive: true });
    const store = createJsonStoreWithExtras({ dir });
    store.putGame(game('#1', '观音误我'));
    store.putGame(game('#2', '观音误我'));
    store.putLog(log({ id: 'L1', gameId: '#1', name: '观音误我 · 0918-1636', state: 'ended', fileName: '观音误我_观音误我 · 0918-1636.txt' }));
    store.putLog(log({ id: 'L2', gameId: '#2', name: '观音误我 · 0918-1639', state: 'ended', fileName: '观音误我_观音误我 · 0918-1639.txt' }));
    writeFileSync(join(logsDir, '观音误我_观音误我 · 0918-1636.txt'), 'A', 'utf8');
    writeFileSync(join(logsDir, '观音误我_观音误我 · 0918-1639.txt'), 'B', 'utf8');

    const result = await migrateLogNames(
      store,
      ['L1', 'L2'],
      (guildId, gameId) => store.getGame(guildId, gameId),
      { logsDir, dryRun: false },
    );
    assert.equal(result.changes.length, 2);
    const first = store.getLog('L1')?.fileName ?? '';
    const second = store.getLog('L2')?.fileName ?? '';
    assert.notEqual(first, second, `导出文件名必须唯一：${first} / ${second}`);
    assert.equal(readFileSync(join(logsDir, first), 'utf8'), 'A', '内容不能互相覆盖');
    assert.equal(readFileSync(join(logsDir, second), 'utf8'), 'B');
    assert.equal(readdirSync(logsDir).length, 2);
  });

  test('目标导出文件已存在时不覆盖，只改记录并给出警告', async () => {    const dir = tempDir('conflict');
    const logsDir = join(dir, 'logs');
    mkdirSync(logsDir, { recursive: true });
    const store = createJsonStoreWithExtras({ dir });
    store.putGame(game('#1', '阿卡姆'));
    store.putLog(log({ id: 'L1', name: '阿卡姆 · 0918-2202', state: 'ended', fileName: 'old.txt' }));
    writeFileSync(join(logsDir, 'old.txt'), '旧', 'utf8');
    writeFileSync(join(logsDir, '阿卡姆.txt'), '已存在', 'utf8');

    const result = await migrateLogNames(
      store,
      ['L1'],
      (guildId, gameId) => store.getGame(guildId, gameId),
      { logsDir, dryRun: false },
    );
    assert.equal(result.renamedFiles.length, 0);
    assert.ok(result.warnings[0]?.includes('未覆盖'), String(result.warnings[0]));
    assert.equal(store.getLog('L1')?.fileName, '阿卡姆.txt');
    assert.equal(basename(join(logsDir, '阿卡姆.txt')), '阿卡姆.txt');
  });
});
